#!/usr/bin/env node
'use strict';

/**
 * Build script for public/sw.js — generates a content-hashed CACHE_NAME
 * so stale service-worker caches rotate automatically when any input changes.
 *
 * Usage:
 *   node scripts/build-sw.js           # Generate/update public/sw.js
 *   node scripts/build-sw.js --check   # Exit 1 if public/sw.js is out-of-date
 */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const PLACEHOLDER = '__GWN_SW_CACHE_NAME__';
const TEMPLATE_PATH = path.join(__dirname, '..', 'public', 'sw.template.js');
const OUTPUT_PATH = path.join(__dirname, '..', 'public', 'sw.js');
const PUBLIC_DIR = path.join(__dirname, '..', 'public');

const HEADER = '// AUTO-GENERATED by scripts/build-sw.js \u2014 do not edit. Run `npm run build:sw` to regenerate.\n';

/**
 * Extract the STATIC_ASSETS array from the template source.
 * Returns sorted, deduplicated path strings.
 */
function extractStaticAssets(templateText) {
  const match = templateText.match(/const STATIC_ASSETS\s*=\s*\[([\s\S]*?)\];/);
  if (!match) {
    throw new Error('Could not find STATIC_ASSETS array in template');
  }
  const paths = [];
  const pathRegex = /'([^']+)'/g;
  let m;
  while ((m = pathRegex.exec(match[1])) !== null) {
    paths.push(m[1]);
  }
  return [...new Set(paths)].sort();
}

/**
 * Compute SHA-256 digest over: template text + sorted STATIC_ASSETS paths + asset file bytes.
 * Returns first 8 hex characters.
 */
function computeDigest(templateText, sortedAssets, publicDir) {
  const hash = crypto.createHash('sha256');

  // 1. Template text
  hash.update(templateText, 'utf8');

  // 2. Sorted asset path list as JSON
  hash.update(JSON.stringify(sortedAssets), 'utf8');

  // 3. Asset file contents in sorted order (as raw buffers)
  const missing = [];
  for (const assetPath of sortedAssets) {
    // Map URL path to filesystem path (e.g. '/' → 'index.html', '/css/style.css' → 'css/style.css')
    let fsRelative = assetPath;
    if (fsRelative === '/') {
      fsRelative = 'index.html';
    } else if (fsRelative.startsWith('/')) {
      fsRelative = fsRelative.slice(1);
    }
    const fullPath = path.join(publicDir, fsRelative);
    if (!fs.existsSync(fullPath)) {
      missing.push(`${assetPath} → ${fullPath}`);
      continue;
    }
    hash.update(fs.readFileSync(fullPath));
  }

  if (missing.length > 0) {
    throw new Error(
      `STATIC_ASSETS references files that don't exist:\n  ${missing.join('\n  ')}`
    );
  }

  return hash.digest('hex').slice(0, 8);
}

/**
 * Generate the sw.js content from template + digest.
 */
function generate(templateText, digest8) {
  const cacheName = `gwn-${digest8}`;
  const body = templateText.replace(PLACEHOLDER, cacheName);
  return HEADER + body;
}

/**
 * Main entry point. Exported for testability.
 */
function main({ checkMode = false, templatePath = TEMPLATE_PATH, outputPath = OUTPUT_PATH, publicDir = PUBLIC_DIR } = {}) {
  const templateText = fs.readFileSync(templatePath, 'utf8');
  const sortedAssets = extractStaticAssets(templateText);
  const digest8 = computeDigest(templateText, sortedAssets, publicDir);
  const freshContent = generate(templateText, digest8);

  if (checkMode) {
    if (!fs.existsSync(outputPath)) {
      console.error(`ERROR: ${outputPath} does not exist. Run \`npm run build:sw\` to generate it.`);
      return { exitCode: 1, digest8 };
    }
    const existing = fs.readFileSync(outputPath, 'utf8');
    if (existing === freshContent) {
      console.log(`OK: public/sw.js is up-to-date (CACHE_NAME = 'gwn-${digest8}')`);
      return { exitCode: 0, digest8 };
    } else {
      console.error(`ERROR: public/sw.js is out-of-date.`);
      console.error(`  Expected CACHE_NAME: gwn-${digest8}`);
      // Extract current CACHE_NAME from existing file for diagnostics
      const currentMatch = existing.match(/CACHE_NAME\s*=\s*'([^']+)'/);
      if (currentMatch) {
        console.error(`  Current  CACHE_NAME: ${currentMatch[1]}`);
      }
      console.error(`Run \`npm run build:sw\` to regenerate.`);
      return { exitCode: 1, digest8 };
    }
  }

  // Write mode
  fs.writeFileSync(outputPath, freshContent, 'utf8');
  console.log(`build:sw → CACHE_NAME = 'gwn-${digest8}'`);
  return { exitCode: 0, digest8 };
}

// CLI entry point
if (require.main === module) {
  const checkMode = process.argv.includes('--check');
  const result = main({ checkMode });
  process.exit(result.exitCode);
}

module.exports = { main, extractStaticAssets, computeDigest, generate, PLACEHOLDER, HEADER };
